---
title: "Inspecting and Manipulating Text Data with Unix Tools - part 5"
output: html_notebook
---

## Sorting Plain-Text Data with Sort

Running sort without any arguments simply sorts a file alphanumerically by line.

By default, sort treats blank characters (like tab or spaces) as field delimiters.
If your file uses another delimiter (such as a comma for CSV files), you can specify the filed separator with -t.

Specify the columns (and their order) we want to sort by as -k arguments.
In technical terms, -k specifies the sorting keys and their order.
Each -k argument takes a range of columns as start, end, so to sort by a single column we use start, start. 
```{}
$ sort -k1,1 -k2,2n example.bed chr1 9 28
chr1 10 19
chr1 26 39
    chr1    32      47
    chr1    40      49
    chr2    35      54
    chr3    11      28
    chr3    16      27
```

Here we first sort by the first column (chromosome), as the first -k argument was -k1, 1.
Sorting by the first column alone leads to many ties in rows the same chromosomes (e.g., "chr1" and "chr3"). Adding a second -k argument with a different column tells sort how to break these ties.
-k2,2n tells sort to sort by the second column (start position), treating this column as numerical data.

We can check if a file is sorted according to our -k arguments using -c:
```{}
$ sort -k1,1 -k2,2n -c example_sorted.bed
$ echo $?
```

If this file is already sorted by -k1,1 -k2,2n -c, sorrt exits with exit status 0 (true).
If not, sort returns the first out-of-order row it finds and exit with status 1 (false).

It’s also possible to sort in reverse order with the -r argument:
```{}
$ sort -k1,1 -k2,2n -r example.bed
```

If you’d like to only reverse the sorting order of a single column, you can append r on that column’s -k argument:
```{}
$ sort -k1,1 -k2,2nr example.bed
```

